version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx-reverse-proxy
    volumes:
      - ./nginx-reverse-proxy/apps_nginx.conf:/etc/nginx/conf.d/apps_nginx.conf
    ports:
      - 80:80
    networks:
      - mynetwork

  streamlit_1:
    build:
      context: ./streamlit_1
      dockerfile: Dockerfile
    container_name: streamlit_1
    working_dir: /app
    volumes:
      - ./streamlit_1:/app
    ports:
      - 8501:8501
    networks:
      - mynetwork

  streamlit_2:
    build:
      context: ./streamlit_2
      dockerfile: Dockerfile
    container_name: streamlit_2
    working_dir: /app
    volumes:
      - ./streamlit_2:/app
    ports:
      - 8502:8502
    networks:
      - mynetwork

networks:
  mynetwork:
